#!/bin/bash


language_list=( "Java" "Python" "Visual Basic" "Javascript" "PHP" "Assembly language" "SQL" "Swift" "MATLAB" "Pascal" "Ruby" "Bash" "Lisp" "Objective-C" "Perl" "Groovy" )

for item in "${language_list[@]}"
do
    echo "$item"
    mongo --eval "db.libraries.insertOne({ name: '${item}' })"
done
mongo --eval 'db.libraries.insertOne({ name: "setuptools", description:  "Easily download, build, install, upgrade, and uninstall Python packages"})'
mongo --eval 'db.libraries.insertOne({ name: "botocore", description:  "Low-level, data-driven core of boto 3."})'
mongo --eval 'db.libraries.insertOne({ name: "urllib3", description:  "HTTP library with thread-safe connection pooling, file post, and more."})'
mongo --eval 'db.libraries.insertOne({ name: "boto3", description:  "The AWS SDK for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "s3transfer", description:  "An Amazon S3 Transfer Manager"})'
mongo --eval 'db.libraries.insertOne({ name: "six", description:  "Python 2 and 3 compatibility utilities"})'
mongo --eval 'db.libraries.insertOne({ name: "python-dateutil", description:  "Extensions to the standard Python datetime module"})'
mongo --eval 'db.libraries.insertOne({ name: "pyyaml", description:  "YAML parser and emitter for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "requests", description:  "Python HTTP for Humans."})'
mongo --eval 'db.libraries.insertOne({ name: "idna", description:  "Internationalized Domain Names in Applications (IDNA)"})'
mongo --eval 'db.libraries.insertOne({ name: "certifi", description:  "Python package for providing Mozilla's CA Bundle."})'
mongo --eval 'db.libraries.insertOne({ name: "awscli", description:  "Universal Command Line Environment for AWS."})'
mongo --eval 'db.libraries.insertOne({ name: "charset-normalizer", description:  "The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet."})'
mongo --eval 'db.libraries.insertOne({ name: "colorama", description:  "Cross-platform colored terminal text."})'
mongo --eval 'db.libraries.insertOne({ name: "rsa", description:  "Pure-Python RSA implementation"})'
mongo --eval 'db.libraries.insertOne({ name: "jmespath", description:  "JSON Matching Expressions"})'
mongo --eval 'db.libraries.insertOne({ name: "pyasn1", description:  "ASN.1 types and codecs"})'
mongo --eval 'db.libraries.insertOne({ name: "wheel", description:  "A built-package format for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "typing-extensions", description:  "Backported and Experimental Type Hints for Python 3.6+"})'
mongo --eval 'db.libraries.insertOne({ name: "packaging", description:  "Core utilities for Python packages"})'
mongo --eval 'db.libraries.insertOne({ name: "numpy", description:  "NumPy is the fundamental package for array computing with Python."})'
mongo --eval 'db.libraries.insertOne({ name: "pip", description:  "The PyPA recommended tool for installing Python packages."})'
mongo --eval 'db.libraries.insertOne({ name: "importlib-metadata", description:  "Read metadata from Python packages"})'
mongo --eval 'db.libraries.insertOne({ name: "pyparsing", description:  "Python parsing module"})'
mongo --eval 'db.libraries.insertOne({ name: "google-api-core", description:  "Google API client core library"})'
mongo --eval 'db.libraries.insertOne({ name: "zipp", description:  "Backport of pathlib-compatible object wrapper for zip files"})'
mongo --eval 'db.libraries.insertOne({ name: "cryptography", description:  "cryptography is a package which provides cryptographic recipes and primitives to Python developers."})'
mongo --eval 'db.libraries.insertOne({ name: "protobuf", description:  "Protocol Buffers"})'
mongo --eval 'db.libraries.insertOne({ name: "pandas", description:  "Powerful data structures for data analysis, time series, and statistics"})'
mongo --eval 'db.libraries.insertOne({ name: "cffi", description:  "Foreign Function Interface for Python calling C code."})'
mongo --eval 'db.libraries.insertOne({ name: "click", description:  "Composable command line interface toolkit"})'
mongo --eval 'db.libraries.insertOne({ name: "markupsafe", description:  "Safely add untrusted strings to HTML/XML markup."})'
mongo --eval 'db.libraries.insertOne({ name: "jinja2", description:  "A very fast and expressive template engine."})'
mongo --eval 'db.libraries.insertOne({ name: "docutils", description:  "Docutils -- Python Documentation Utilities"})'
mongo --eval 'db.libraries.insertOne({ name: "attrs", description:  "Classes Without Boilerplate"})'
mongo --eval 'db.libraries.insertOne({ name: "pytz", description:  "World timezone definitions, modern and historical"})'
mongo --eval 'db.libraries.insertOne({ name: "pyjwt", description:  "JSON Web Token implementation in Python"})'
mongo --eval 'db.libraries.insertOne({ name: "pycparser", description:  "C parser in Python"})'
mongo --eval 'db.libraries.insertOne({ name: "google-auth", description:  "Google Authentication Library"})'
mongo --eval 'db.libraries.insertOne({ name: "oauthlib", description:  "A generic, spec-compliant, thorough implementation of the OAuth request-signing logic"})'
mongo --eval 'db.libraries.insertOne({ name: "requests-oauthlib", description:  "OAuthlib authentication support for Requests."})'
mongo --eval 'db.libraries.insertOne({ name: "cachetools", description:  "Extensible memoizing collections and decorators"})'
mongo --eval 'db.libraries.insertOne({ name: "pyasn1-modules", description:  "A collection of ASN.1-based protocols modules."})'
mongo --eval 'db.libraries.insertOne({ name: "google-cloud-core", description:  "Google Cloud API client core library"})'
mongo --eval 'db.libraries.insertOne({ name: "sqlalchemy", description:  "Database Abstraction Library"})'
mongo --eval 'db.libraries.insertOne({ name: "wrapt", description:  "Module for decorators, wrappers and monkey patching."})'
mongo --eval 'db.libraries.insertOne({ name: "chardet", description:  "Universal encoding detector for Python 2 and 3"})'
mongo --eval 'db.libraries.insertOne({ name: "werkzeug", description:  "The comprehensive WSGI web application library."})'
mongo --eval 'db.libraries.insertOne({ name: "google-cloud-storage", description:  "Google Cloud Storage API client library"})'
mongo --eval 'db.libraries.insertOne({ name: "azure-core", description:  "Microsoft Azure Core Library for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "isodate", description:  "An ISO 8601 date/time/duration parser and formatter"})'
mongo --eval 'db.libraries.insertOne({ name: "toml", description:  "Python Library for Tom's Obvious, Minimal Language"})'
mongo --eval 'db.libraries.insertOne({ name: "aiohttp", description:  "Async http client/server framework (asyncio)"})'
mongo --eval 'db.libraries.insertOne({ name: "websocket-client", description:  "WebSocket client for Python with low level API options"})'
mongo --eval 'db.libraries.insertOne({ name: "flask", description:  "A simple framework for building complex web applications."})'
mongo --eval 'db.libraries.insertOne({ name: "googleapis-common-protos", description:  "Common protobufs used in Google APIs"})'
mongo --eval 'db.libraries.insertOne({ name: "multidict", description:  "multidict implementation"})'
mongo --eval 'db.libraries.insertOne({ name: "yarl", description:  "Yet another URL library"})'
mongo --eval 'db.libraries.insertOne({ name: "decorator", description:  "Decorators for Humans"})'
mongo --eval 'db.libraries.insertOne({ name: "greenlet", description:  "Lightweight in-process concurrent programming"})'
mongo --eval 'db.libraries.insertOne({ name: "psutil", description:  "Cross-platform lib for process and system monitoring in Python."})'
mongo --eval 'db.libraries.insertOne({ name: "tabulate", description:  "Pretty-print tabular data"})'
mongo --eval 'db.libraries.insertOne({ name: "py", description:  "library with cross-python path, ini-parsing, io, code, log facilities"})'
mongo --eval 'db.libraries.insertOne({ name: "async-timeout", description:  "Timeout context manager for asyncio programs"})'
mongo --eval 'db.libraries.insertOne({ name: "jsonschema", description:  "An implementation of JSON Schema validation for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "azure-storage-blob", description:  "Microsoft Azure Blob Storage Client Library for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "msrest", description:  "AutoRest swagger generator Python client runtime."})'
mongo --eval 'db.libraries.insertOne({ name: "google-api-python-client", description:  "Google API Client Library for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "pyarrow", description:  "Python library for Apache Arrow"})'
mongo --eval 'db.libraries.insertOne({ name: "itsdangerous", description:  "Safely pass data to untrusted environments and back."})'
mongo --eval 'db.libraries.insertOne({ name: "grpcio", description:  "HTTP/2-based RPC framework"})'
mongo --eval 'db.libraries.insertOne({ name: "pillow", description:  "Python Imaging Library (Fork)"})'
mongo --eval 'db.libraries.insertOne({ name: "pyrsistent", description:  "Persistent/Functional/Immutable data structures"})'
mongo --eval 'db.libraries.insertOne({ name: "docker", description:  "A Python library for the Docker Engine API."})'
mongo --eval 'db.libraries.insertOne({ name: "scipy", description:  "SciPy: Scientific Library for Python"})'
mongo --eval 'db.libraries.insertOne({ name: "fsspec", description:  "File-system specification"})'
mongo --eval 'db.libraries.insertOne({ name: "lxml", description:  "Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API."})'
mongo --eval 'db.libraries.insertOne({ name: "pytest", description:  "pytest: simple powerful testing with Python"})'
mongo --eval 'db.libraries.insertOne({ name: "frozenlist", description:  "A list-like structure which implements collections.abc.MutableSequence"})'
mongo --eval 'db.libraries.insertOne({ name: "filelock", description:  "A platform independent file lock."})'
mongo --eval 'db.libraries.insertOne({ name: "pluggy", description:  "plugin and hook calling mechanisms for python"})'
mongo --eval 'db.libraries.insertOne({ name: "pygments", description:  "Pygments is a syntax highlighting package written in Python."})'
mongo --eval 'db.libraries.insertOne({ name: "futures", description:  "Backport of the concurrent.futures package from Python 3"})'
mongo --eval 'db.libraries.insertOne({ name: "importlib-resources", description:  "Read resources from Python packages"})'
mongo --eval 'db.libraries.insertOne({ name: "tqdm", description:  "Fast, Extensible Progress Meter"})'
mongo --eval 'db.libraries.insertOne({ name: "azure-common", description:  "Microsoft Azure Client Library for Python (Common)"})'
mongo --eval 'db.libraries.insertOne({ name: "aiosignal", description:  "aiosignal: a list of registered asynchronous callbacks"})'
mongo --eval 'db.libraries.insertOne({ name: "future", description:  "Clean single-source support for Python 3 and 2"})'
mongo --eval 'db.libraries.insertOne({ name: "google-resumable-media", description:  "Utilities for Google Media Downloads and Resumable Uploads"})'
mongo --eval 'db.libraries.insertOne({ name: "google-cloud-bigquery", description:  "Google BigQuery API client library"})'
mongo --eval 'db.libraries.insertOne({ name: "gitpython", description:  "GitPython is a python library used to interact with Git repositories"})'
mongo --eval 'db.libraries.insertOne({ name: "joblib", description:  "Lightweight pipelining with Python functions"})'
mongo --eval 'db.libraries.insertOne({ name: "mypy-extensions", description:  "Experimental type system extensions for programs checked with the mypy typechecker."})'
mongo --eval 'db.libraries.insertOne({ name: "platformdirs", description:  "A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir"."})'
mongo --eval 'db.libraries.insertOne({ name: "prometheus-client", description:  "Python client for the Prometheus monitoring system."})'
mongo --eval 'db.libraries.insertOne({ name: "gunicorn", description:  "WSGI HTTP Server for UNIX"})'
mongo --eval 'db.libraries.insertOne({ name: "matplotlib", description:  "Python plotting package"})'
mongo --eval 'db.libraries.insertOne({ name: "pyopenssl", description:  "Python wrapper module around the OpenSSL library"})'
mongo --eval 'db.libraries.insertOne({ name: "smmap", description:  "A pure Python implementation of a sliding window memory map manager"})'
mongo --eval 'db.libraries.insertOne({ name: "httplib2", description:  "A comprehensive HTTP client library."})'
